fix: login feature using cookies to save access token
AvengersTraining/frontend_ojt_training pull request #24
Opened 2023-09-27 05:45 UTC by anhdd-3363

- Sửa logic đăng nhập sử dụng cookies để lưu access token, tránh việc F5 bị mất trạng thái

2023-09-28 02:17 UTC, ductt-3362 commented on src/router/index.js
> +      return;
bổ sung cho cả phần đăng ký

2023-09-28 02:17 UTC, ductt-3362 commented on src/stores/auth.js
> +// import decodeJwt from "jwt-decode";
remove

2023-09-28 02:17 UTC, ductt-3362 commented on src/views/LoginView.vue
> +    $toast.error(error);
dùng  `$toast.error(loginMessage.error);`

2023-09-28 11:34 UTC, binhth-1206 requested changes

2023-09-28 11:34 UTC, binhth-1206 commented on src/stores/auth.js
> +      window.location.replace("/");
Thay vì phải reload lại trang thì mình thấy bạn nên move code này ra func handleLogin. Login -> set state -> router.push('/')

2023-09-28 11:34 UTC, binhth-1206 commented on src/stores/auth.js
> +    identity: null,
Suggestion: replace `identity` === `userInfo`

2023-09-29 03:43 UTC, binhth-1206 approved these changes

2023-09-29 03:43 UTC, merged